resilience4j:
  circuitbreaker:
    configs:
      my-resilience4j-config:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      items:
        base-config: my-resilience4j-config
  timelimiter:
    configs:
      my-timeout-config:
        timeout-duration: 4s
    instances:
      items:
        base-config: my-timeout-config

